plan/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.contrib.auth import views as auth_views

from . import views 
app_name = 'plan'


router = DefaultRouter()
router.register(r'info', views.InfoFormViewSet)
router.register(r'actual-returns', views.ActualReturnsViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.homepag, name='homepag'),
    path('index', views.index, name='homepage'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.registerUser, name='register'),
    path('pricing.html', views.pricing, name='pricing'),
    path('stock-markets.html', views.stockMarkets, name='stock-markets'),
    path('trading-view.html', views.tradindViwe, name='trading-view'),
    path('journal-trades.html', views.journals, name='journal-trades'),
   # path('insert', views.insertData, name='insertData'),
   # path('delete/<id>/', views.delete_data, name="delete" ),
   # path('update/<id>/', views.update_data, name="update" ),
    path('reset_password', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password" ),    
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_confirm.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
   # path('adddata', views.addand, name='adddata'),
   # path('updatee', views.uppddaattee, name='updatte'),
    path('trading-business-plan.html', views.trading_business_plan, name='rading-business-plan'),
    #path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',views.activate,name="activate")
    
]

tradingDemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plan.urls', namespace='plan')),
    path('accounts/', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
  
]

templates/addandshowdara.html
{% extends "trading-business-plan.html" %}

{% block content %}

<h4> JOURNAL YOUR TRADERS </h4>

{% endblock content %}

templates/homepag.html
{% load static %} 

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My Dashboard | HashForexUG</title>
  <link rel="shortcut icon" type="image/png" href="assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="/" class="text-nowrap logo-img">
            <img src="{% static 'assets/images/logos/dark-logo.png' %}" width="180" alt="" />
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Navigation</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="/" aria-expanded="false">
                <span>
                  <i class="ti ti-home"></i>
                </span>
                <span class="hide-menu">My Dashboard</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="pricing.html" aria-expanded="false">
                <span>
                  <i class="ti ti-businessplan"></i>
                </span>
                <span class="hide-menu">Pricing</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="https://hashforexug.com/live-chat/" target="_blank" aria-expanded="false">
                <span>
                  <i class="ti ti-brand-hipchat"></i>
                </span>
                <span class="hide-menu">Live Chat</span>
              </a>
            </li>
            
             <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Risk Management</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="journal-trades.html" aria-expanded="false">
                <span>
                  <i class="ti ti-notes"></i>
                </span>
                <span class="hide-menu">Journal Your Trades</span>
              </a>
            </li> 
             <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'plan:homepage' %}" aria-expanded="false">
                <span>
                  <i class="ti ti-chart-infographic"></i>
                </span>
                <span class="hide-menu">Trading Plan </span>
              </a>
            </li>   
            <li class="sidebar-item">
              <a class="sidebar-link" href="trading-business-plan.html" aria-expanded="false">
                <span>
                  <i class="ti ti-chart-infographic"></i>
                </span>
                <span class="hide-menu">Trading Psychology</span>
              </a>
            </li> 
            

            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Markets</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="trading-view.html" aria-expanded="false">
                <span>
                  <i class="ti ti-timeline"></i>
                </span>
                <span class="hide-menu">Trading VIew</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="stock-markets.html" aria-expanded="false">
                <span>
                  <i class="ti ti-chart-line"></i>
                </span>
                <span class="hide-menu">Stock Markets</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Support</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="javascript:void(0)" aria-expanded="false">
                <span>
                  <i class="ti ti-help"></i>
                </span>
                <span class="hide-menu">Support Centre</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="https://hashforexug.com/contact-us/" target="_blank" aria-expanded="false">
                <span>
                  <i class="ti ti-phone"></i>
                </span>
                <span class="hide-menu">Contact Us</span>
              </a>
            </li>


            
          </ul>
          
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header Start -->
      <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
              <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                <i class="ti ti-menu-2"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                <i class="ti ti-bell-ringing"></i>
                <div class="notification bg-primary rounded-circle"></div>
              </a>
            </li>
          </ul>
          <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
              <a href="{% url 'plan:logout' %}" class="btn btn-primary m-1">Logout</a>
              
            </ul>
          </div>
        </nav>
      </header>
      <!--  Header End -->
      <div class="container-fluid">
        
<!-- Insert content Here-->


                                     <!-- TradingView Widget BEGIN -->
        
               <div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text"></span></a></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
    {
    "symbols"; [
      {
        "proName": "FOREXCOM:SPXUSD",
        "title": "S&P 500"
      },
      {
        "proName": "FOREXCOM:NSXUSD",
        "title": "US 100"
      },
      {
        "proName": "FX_IDC:EURUSD",
        "title": "EUR to USD"
      },
      {
        "proName": "BITSTAMP:BTCUSD",
        "title": "Bitcoin"
      },
      {
        "proName": "BITSTAMP:ETHUSD",
        "title": "Ethereum"
      },
      {
        "description": "Gold",
        "proName": "FOREXCOM:XAUUSD"
      }
    ],
    "showSymbolLogo"; false,
    "colorTheme"; "dark",
    "isTransparent"; false,
    "largeChartUrl"; "https://tradingview.deriv.com/deriv",
    "displayMode"; "regular",
    "locale"; "en"
  }
    </script>
  </div>
  <!-- TradingView Widget END -->

  <!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text"></span></a></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-screener.js" async>
    {
    "width"; 1100,
    "height"; 523,
    "defaultColumn"; "overview",
    "defaultScreen"; "general",
    "market"; "forex",
    "showToolbar"; true,
    "colorTheme"; "light",
    "locale"; "en"
  }
    </script>
  </div>
  <!-- TradingView Widget END -->


  <!-- TradingView Widget BEGIN -->
  <h1>Forex Factory (Economic Calander)</h1>
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text"></span></a></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-events.js" async>
    {
    "colorTheme"; "light",
    "isTransparent"; false,
    "width"; "1000",
    "height"; "610",
    "locale"; "en",
    "importanceFilter"; "0,1",
    "countryFilter"; "us,eu,it,nz,ch,au,fr,jp,za,tr,ca,de,mx,es,gb"
  }
    </script>
  </div>
  <!-- TradingView Widget END -->

    <!-- TradingView Widget BEGIN -->
    <h1>Top Stories</h1>
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text"></span></a></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-timeline.js" async>
    {
    "feedMode"; "all_symbols",
    "colorTheme"; "light",
    "isTransparent"; false,
    "displayMode"; "regular",
    "width"; 480,
    "height"; 830,
    "locale"; "en"
  }
    </script>
  </div>
   </div>
  <!-- TradingView Widget END -->






<!--Conntent Ends Here-->

<!--Footer Stars Here-->

        <div class="py-6 px-6 text-center">
          <p class="mb-0 fs-4">Copyright © 2024 Hash Forex Uganda. All Rights Reserved</p>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/sidebarmenu.js' %}"></script>
  <script src="{% static 'assets/js/app.min.js' %}"></script>
  <script src="{% static 'assets/libs/apexcharts/dist/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/libs/simplebar/dist/simplebar.js' %}"></script>
  <script src="{% static 'assets/js/dashboard.js' %}"></script>
</body>

</html>

templates/journals.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/login.html
{% load static %}
{% load socialaccount %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login | HashForexUG</title>
  <link rel="shortcut icon" type="image/png" href="assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <div
      class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
      <div class="d-flex align-items-center justify-content-center w-100">
        <div class="row justify-content-center w-100">
          <div class="col-md-8 col-lg-6 col-xxl-3">
            <div class="card mb-0">
              <div class="card-body">
                <a href="index.html" class="text-nowrap logo-img text-center d-block py-3 w-100">
                  <img src="{% static 'assets/images/logos/dark-logo2.png' %}" width="180" alt="">
                </a>
                <p class="text-center">Be Your Best Trader</p>

              
                <form method="post" action="{% url 'plan:login' %}" class="form">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Username</label>
                    <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp">
                  </div>
                  <div class="mb-4">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password" id="exampleInputPassword1">
                  </div>
                  <div class="d-flex align-items-center justify-content-between mb-4">
                    <div class="form-check">
                      <input class="form-check-input primary" type="checkbox" value="" id="flexCheckChecked" checked>
                      <label class="form-check-label text-dark" for="flexCheckChecked">
                        Remember Me
                      </label>
                    </div>
                    <a class="text-primary fw-bold" href="{% url 'plan:reset_password' %}">Forgot Password ?</a>
                  </div>
                  <div>
                  <button class="btn btn-warning w-100 py-8 fs-4 mb-4 rounded-2">Sign In</a>
                </div>




                  <div class="d-flex align-items-center justify-content-center">
                    <p class="fs-4 mb-0 fw-bold">Are You New Here?</p>
                    <a class="text-primary fw-bold ms-2" href="{% url 'plan:register' %}">Create an account</a>
                  </div>
                </form>

               
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/pricing.html
{%load static%}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Pricing | HashForexUG</title>
  <link rel="shortcut icon" type="image/png" href="assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />

   <!-- pricing styles starts here-->
            <!-- Favicons -->
        <link href="img/favicon.ico" rel="icon">
        <link href="img/apple-touch-icon.png" rel="apple-touch-icon">
        
        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:300,600,900|Raleway:300,400,500&display=swap" rel="stylesheet">  

        <!-- Font Awesome Icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Main Stylesheet File -->
        <link href="{% static './assets/css/price.css' %}" rel="stylesheet">
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="/" class="text-nowrap logo-img">
            <img src="{% static 'assets/images/logos/dark-logo.png' %}" width="180" alt="" />
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Navigation</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="/" aria-expanded="false">
                <span>
                  <i class="ti ti-home"></i>
                </span>
                <span class="hide-menu">My Dashboard</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="pricing.html" aria-expanded="false">
                <span>
                  <i class="ti ti-businessplan"></i>
                </span>
                <span class="hide-menu">Pricing</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="https://hashforexug.com/live-chat/" target="_blank" aria-expanded="false">
                <span>
                  <i class="ti ti-brand-hipchat"></i>
                </span>
                <span class="hide-menu">Live Chat</span>
              </a>
            </li>
            
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Risk Management</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="journal-trades.html" aria-expanded="false">
                <span>
                  <i class="ti ti-notes"></i>
                </span>
                <span class="hide-menu">Journal Your Trades</span>
              </a>
            </li> 
             <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'plan:homepage' %}" aria-expanded="false">
                <span>
                  <i class="ti ti-chart-infographic"></i>
                </span>
                <span class="hide-menu">Trading Plan </span>
              </a>
            </li> 
            <li class="sidebar-item">
              <a class="sidebar-link" href="trading-business-plan.html" aria-expanded="false">
                <span>
                  <i class="ti ti-chart-infographic"></i>
                </span>
                <span class="hide-menu">Trading Psychology</span>
              </a>
            </li> 

            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Markets</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="trading-view.html" aria-expanded="false">
                <span>
                  <i class="ti ti-timeline"></i>
                </span>
                <span class="hide-menu">Trading VIew</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="stock-markets.html" aria-expanded="false">
                <span>
                  <i class="ti ti-chart-line"></i>
                </span>
                <span class="hide-menu">Stock Markets</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Support</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="javascript:void(0)" aria-expanded="false">
                <span>
                  <i class="ti ti-help"></i>
                </span>
                <span class="hide-menu">Support Centre</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="https://hashforexug.com/contact-us/" target="_blank" aria-expanded="false">
                <span>
                  <i class="ti ti-phone"></i>
                </span>
                <span class="hide-menu">Contact Us</span>
              </a>
            </li>


            
          </ul>
          
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header Start -->
      <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
              <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                <i class="ti ti-menu-2"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                <i class="ti ti-bell-ringing"></i>
                <div class="notification bg-primary rounded-circle"></div>
              </a>
            </li>
          </ul>
          <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
              <a href="{% url 'plan:logout' %}" class="btn btn-primary m-1">Logout</a>
              
            </ul>
          </div>
        </nav>
      </header>
      <!--  Header End -->
      <div class="container-fluid">
        
<!-- Insert content Here-->

<!-- Pricing Starts Here-->  
   
  <!-- Pricing Table 5 Start -->
        <div class="pricing-table-title">
            <h2>Our Prices</h2>
        </div>
        <div class="pricing-table table-5">
            <div class="ptable-item">
                <div class="ptable-single">
                    <div class="ptable-header">
                        <div class="ptable-title">
                           <h2>FREE PLAN</h2>
                        </div>
                        <div class="ptable-price">
                            <h2><small>$</small>0<span>/ M</span></h2>
                        </div>
                    </div>
                   
                    <div class="ptable-body">
                        <div class="ptable-description">
                            <ul>
                                <li>Free Live Community Access</li>
                                <li>Basic Trading Education</li>
                                <li>Private Live Community Access</li>
                                <li>Basic trading Tools</li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="ptable-footer">
                        <div class="ptable-action">
                            <a href="https://hashforexug.com/lets-get-started/"><i class="fa fa-shopping-cart"></i>Choose Plan</a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="ptable-item featured-item">
                <div class="ptable-single">
                    <div class="ptable-header">
                        <div class="ptable-status">
                            <span>Hot</span>
                        </div>
                        <div class="ptable-title">
                            <h2>Get Monitored</h2>
                        </div>
                        <div class="ptable-price">
                            <h2><small>$</small>256<span></span></h2>
                        </div>
                        <div class="ptable-title">
                            <h2>Life-Time</h2>
                        </div>

                    </div>
                    <div class="ptable-body">
                        <div class="ptable-description">
                            <ul>
                                <li>Master the Skill of Price Action Trading</li>
                                <li>Unlimited Learning Access</li>
                                <li>24/7 Technical Support</li>
                                <li>FX Trading Plan</li>
                                <li>Psychology & Mindset</li>
                                <li>Easy to Use</li>
                            </ul>
                        </div>
                    </div>
                    <div class="ptable-footer">
                        <div class="ptable-action">
                            <a href="https://hashforexug.com/lets-get-started/"><i class="fa fa-shopping-cart"></i>choose Plan</a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="ptable-item">
                <div class="ptable-single">
                    <div class="ptable-header">
                        <div class="ptable-title">
                            <h2>Private Live Trading</h2>
                        </div>
                        <div class="ptable-price">
                            <h2><small>$</small>500<span>/ M</span></h2>
                        </div>
                    </div>
                    <div class="ptable-body">
                        <div class="ptable-description">
                            <ul>
                                <li>Daily Live Trading</li>
                                <li>Deep Price Plan</li>
                                <li>24/7 Technical Support</li>
                                <li>Chart Analysis</li>
                                <li>Mentorship</li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="ptable-footer">
                        <div class="ptable-action">
                            <a href="https://hashforexug.com/lets-get-started/"><i class="fa fa-shopping-cart"></i>Choose Plan</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pricing Table 5 End -->

    <!--Pricing Ends Here-->>                    








<!--Conntent Ends Here-->

<!--Footer Stars Here-->

        <div class="py-6 px-6 text-center">
          <p class="mb-0 fs-4">Copyright © 2024 Hash Forex Uganda. All Rights Reserved</p>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/sidebarmenu.js' %}"></script>
  <script src="{% static 'assets/js/app.min.js' %}"></script>
  <script src="{% static 'assets/libs/apexcharts/dist/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/libs/simplebar/dist/simplebar.js' %}"></script>
  <script src="{% static 'assets/js/dashboard.js' %}"></script>
</body>

</html>

templates/register.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sign Up | HashForexUG</title>
  <link rel="shortcut icon" type="image/png" href="assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <div
      class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
      <div class="d-flex align-items-center justify-content-center w-100">
        <div class="row justify-content-center w-100">
          <div class="col-md-8 col-lg-6 col-xxl-3">
            <div class="card mb-0">
              <div class="card-body">
                <a href="index.html" class="text-nowrap logo-img text-center d-block py-3 w-100">
                  <img src="{% static 'assets/images/logos/dark-logo2.png' %}" width="180" alt="">
                </a>
                <p class="text-center">Be Your Best Trader</p>
                     
                
                <form  method="post">
                  {% csrf_token %}

                 

                  {% for field in form %}
            

                      

                  <div class="mb-3">
                    <label for="exampleInputtext1" class="form-label">{{field.label}}</label>
                    {{field}}
                  </div>
                


                  {%  endfor  %}
                  <div class="mb-4">
                    <input class="btn btn-primary w-100 py-8 fs-4 mb-4 rounded-2" type="submit" value="SignUp" >
                  </div>
                  
                  <div class="d-flex align-items-center justify-content-center">
                    <p class="fs-4 mb-0 fw-bold">Already have an Account?</p>
                    <a class="text-primary fw-bold ms-2" href="{% url 'plan:login' %}">Sign In</a>
                  </div>

                  
                  


  <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>